apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: test-ingress-4
configMapGenerator:
- name: test-ingress-4-configmap
  envs:
  - .env
generatorOptions:
  disableNameSuffixHash: true # use a static name
kind: Kustomization
resources:
- deployment.yaml
- service.yaml